// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Color11;
lv_obj_t * ui_Color21;
lv_obj_t * ui_Color31;
lv_obj_t * ui_Color41;
lv_obj_t * ui_Color51;
lv_obj_t * ui_Color61;
lv_obj_t * ui_Color11g;
lv_obj_t * ui_Color21g;
lv_obj_t * ui_Color31g;
lv_obj_t * ui_Color41g;
lv_obj_t * ui_Color51g;
lv_obj_t * ui_Color61g;
lv_obj_t * ui_WireText1;
lv_obj_t * ui_WireText2;
lv_obj_t * ui_WireText3;
lv_obj_t * ui_WireText4;
lv_obj_t * ui_WireText5;
lv_obj_t * ui_WireText6;
lv_obj_t * ui_Locatext1;
lv_obj_t * ui_Locatext2;
lv_obj_t * ui_Locatext3;
lv_obj_t * ui_Locatext4;
lv_obj_t * ui_Locatext5;
lv_obj_t * ui_Locatext6;
lv_obj_t * ui_Wifi;
lv_obj_t * ui_WifiStatus;
lv_obj_t * ui_Wifi4;
lv_obj_t * ui_WireCount;
lv_obj_t * ui_TCP;
lv_obj_t * ui_TCPStatus;
lv_obj_t * ui_Bat;
lv_obj_t * ui_PercentBat;
lv_obj_t * ui_ModeCL;
lv_obj_t * ui_Blink1;
lv_obj_t * ui_Blink2;
lv_obj_t * ui_BlinkLoca;
lv_obj_t * ui_WireCheckLoca;
lv_obj_t * ui_Mode;
lv_obj_t * ui_Color12;
lv_obj_t * ui_Color22;
lv_obj_t * ui_Color32;
lv_obj_t * ui_Color42;
lv_obj_t * ui_Color52;
lv_obj_t * ui_Color62;
lv_obj_t * ui_Color12g;
lv_obj_t * ui_Color22g;
lv_obj_t * ui_Color32g;
lv_obj_t * ui_Color42g;
lv_obj_t * ui_Color52g;
lv_obj_t * ui_Color62g;
lv_obj_t * ui_Color13;
lv_obj_t * ui_Color23;
lv_obj_t * ui_Color33;
lv_obj_t * ui_Color43;
lv_obj_t * ui_Color53;
lv_obj_t * ui_Color63;
lv_obj_t * ui_Color13g;
lv_obj_t * ui_Color23g;
lv_obj_t * ui_Color33g;
lv_obj_t * ui_Color43g;
lv_obj_t * ui_Color53g;
lv_obj_t * ui_Color63g;
lv_obj_t * ui_PanelMode;
lv_obj_t * ui_Highlight1;
lv_obj_t * ui_Highlight2;
lv_obj_t * ui_Highlight3;
lv_obj_t * ui_Highlight4;
lv_obj_t * ui_Highlight5;
lv_obj_t * ui_Highlight6;
// CUSTOM VARIABLES
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    // LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
