// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#ifndef _CODE_LOCATION_COLOR_UI_H
#define _CODE_LOCATION_COLOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../managed_components/lvgl__lvgl/lvgl.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "esp_err.h"
#include "esp_log.h"
#include "string.h"
#include <ctype.h>
#include "freertos/timers.h"
#include "lvgl.h"
// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "TCP_CLIENT_V4.h"
#define LV_COLOR_16_SWAP 0

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Color1;
extern lv_obj_t * ui_Color1g;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_Wifi4;
extern lv_obj_t * ui_WifiStatus;
extern lv_obj_t * ui_TCP;
extern lv_obj_t * ui_TCPStatus;
extern lv_obj_t * ui_Bat;
extern lv_obj_t * ui_PercentBat;
extern lv_obj_t * ui_SAText;
extern lv_obj_t * ui_GroupText;
extern lv_obj_t * ui_Blink1;
extern lv_obj_t * ui_Blink2;
extern lv_obj_t * ui_ModeCL;
extern lv_obj_t * ui_WireCount;
extern lv_obj_t * ui_ColorText;







void ui_init(void);
void lcd_reset_daydien_text(uint8_t index);
void lcd_set_daydien_text(wire_infor* DayDien, uint8_t index, Work_Mode Mode);
void lcd_set_wifi_rssi (int8_t rssi) ;

void lcd_set_socket_status(uint8_t status);
void setWireText (uint8_t wireIndex, char* value, uint16_t valueLength);
void trim(char* str);
lv_color_t map_color(const char* colorCode);

void start_blink_effect(lv_obj_t *obj1, lv_obj_t *obj2);
void end_blink_effect(lv_obj_t *obj1, lv_obj_t *obj2);

void start_blink_effect_OK(void);
void end_blink_effect_OK(void);
void start_blink_effect_NG(void);
void end_blink_effect_NG(void);
void Check_ModeCL_Screen(Work_Mode status);
void set_numberCardOnScreen(uint8_t numberCard);
void set_numberCardOnScreenCL(uint8_t numberCard);
void set_HideObject(lv_obj_t * ui_Object);
void set_ShowObject(lv_obj_t * ui_Object);

void lcd_set_bat_percent (int8_t bat);
void lcd_set_wifi_color (uint8_t isConnectedWifi, int8_t rssi) ;

void lcd_aliveWire (int8_t wireCount) ;
void concat_with_colon(const char* A, const char* B, char* out, size_t out_size);
void concat_three_with_colon(const char* A, const char* B, const char* C, char* out, size_t out_size);
ScreenCL_Mode get_screen_mode(const char* code);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
