// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xB7B6BA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color11, 45);
    lv_obj_set_height(ui_Color11, 21);
    lv_obj_set_x(ui_Color11, -80);
    lv_obj_set_y(ui_Color11, -55);
    lv_obj_set_align(ui_Color11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color21 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color21, 45);
    lv_obj_set_height(ui_Color21, 21);
    lv_obj_set_x(ui_Color21, -80);
    lv_obj_set_y(ui_Color21, -32);
    lv_obj_set_align(ui_Color21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color31 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color31, 45);
    lv_obj_set_height(ui_Color31, 21);
    lv_obj_set_x(ui_Color31, -80);
    lv_obj_set_y(ui_Color31, -9);
    lv_obj_set_align(ui_Color31, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color41 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color41, 45);
    lv_obj_set_height(ui_Color41, 21);
    lv_obj_set_x(ui_Color41, -80);
    lv_obj_set_y(ui_Color41, 14);
    lv_obj_set_align(ui_Color41, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color51 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color51, 45);
    lv_obj_set_height(ui_Color51, 21);
    lv_obj_set_x(ui_Color51, -80);
    lv_obj_set_y(ui_Color51, 37);
    lv_obj_set_align(ui_Color51, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color51, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color51, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color61 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color61, 45);
    lv_obj_set_height(ui_Color61, 21);
    lv_obj_set_x(ui_Color61, -80);
    lv_obj_set_y(ui_Color61, 60);
    lv_obj_set_align(ui_Color61, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color61, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color11g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color11g, 45);
    lv_obj_set_height(ui_Color11g, 7);
    lv_obj_set_x(ui_Color11g, -80);
    lv_obj_set_y(ui_Color11g, -55);
    lv_obj_set_align(ui_Color11g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color11g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color11g, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color11g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Color11g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Color11g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color11g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Color11g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Color21g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color21g, 45);
    lv_obj_set_height(ui_Color21g, 7);
    lv_obj_set_x(ui_Color21g, -80);
    lv_obj_set_y(ui_Color21g, -32);
    lv_obj_set_align(ui_Color21g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color21g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color21g, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color21g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Color21g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Color21g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color21g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Color21g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Color31g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color31g, 45);
    lv_obj_set_height(ui_Color31g, 7);
    lv_obj_set_x(ui_Color31g, -80);
    lv_obj_set_y(ui_Color31g, -9);
    lv_obj_set_align(ui_Color31g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color31g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color31g, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color31g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Color31g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Color31g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color31g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Color31g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Color41g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color41g, 45);
    lv_obj_set_height(ui_Color41g, 7);
    lv_obj_set_x(ui_Color41g, -80);
    lv_obj_set_y(ui_Color41g, 14);
    lv_obj_set_align(ui_Color41g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color41g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color41g, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color41g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Color41g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Color41g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color41g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Color41g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Color51g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color51g, 45);
    lv_obj_set_height(ui_Color51g, 7);
    lv_obj_set_x(ui_Color51g, -80);
    lv_obj_set_y(ui_Color51g, 37);
    lv_obj_set_align(ui_Color51g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color51g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color51g, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color51g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Color51g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Color51g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color51g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Color51g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Color61g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color61g, 45);
    lv_obj_set_height(ui_Color61g, 7);
    lv_obj_set_x(ui_Color61g, -80);
    lv_obj_set_y(ui_Color61g, 60);
    lv_obj_set_align(ui_Color61g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color61g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color61g, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color61g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Color61g, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Color61g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color61g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Color61g, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_WireText1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireText1, 65);
    lv_obj_set_height(ui_WireText1, 18);
    lv_obj_set_x(ui_WireText1, -16);
    lv_obj_set_y(ui_WireText1, -55);
    lv_obj_set_align(ui_WireText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireText1, "AB001");
    lv_obj_set_style_text_font(ui_WireText1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireText2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireText2, 65);
    lv_obj_set_height(ui_WireText2, 18);
    lv_obj_set_x(ui_WireText2, -16);
    lv_obj_set_y(ui_WireText2, -32);
    lv_obj_set_align(ui_WireText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireText2, "AB002\n");
    lv_obj_set_style_text_font(ui_WireText2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireText3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireText3, 65);
    lv_obj_set_height(ui_WireText3, 18);
    lv_obj_set_x(ui_WireText3, -16);
    lv_obj_set_y(ui_WireText3, -9);
    lv_obj_set_align(ui_WireText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireText3, "AB003");
    lv_obj_set_style_text_font(ui_WireText3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireText4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireText4, 65);
    lv_obj_set_height(ui_WireText4, 18);
    lv_obj_set_x(ui_WireText4, -16);
    lv_obj_set_y(ui_WireText4, 14);
    lv_obj_set_align(ui_WireText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireText4, "AB004");
    lv_obj_set_style_text_font(ui_WireText4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireText5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireText5, 65);
    lv_obj_set_height(ui_WireText5, 18);
    lv_obj_set_x(ui_WireText5, -16);
    lv_obj_set_y(ui_WireText5, 37);
    lv_obj_set_align(ui_WireText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireText5, "AB005");
    lv_obj_set_style_text_font(ui_WireText5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireText6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireText6, 65);
    lv_obj_set_height(ui_WireText6, 18);
    lv_obj_set_x(ui_WireText6, -16);
    lv_obj_set_y(ui_WireText6, 60);
    lv_obj_set_align(ui_WireText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireText6, "AB006\n");
    lv_obj_set_style_text_font(ui_WireText6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Locatext1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locatext1, 65);
    lv_obj_set_height(ui_Locatext1, 18);
    lv_obj_set_x(ui_Locatext1, 53);
    lv_obj_set_y(ui_Locatext1, -55);
    lv_obj_set_align(ui_Locatext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locatext1, "Loca1\n");
    lv_obj_set_style_text_font(ui_Locatext1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Locatext2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locatext2, 65);
    lv_obj_set_height(ui_Locatext2, 18);
    lv_obj_set_x(ui_Locatext2, 53);
    lv_obj_set_y(ui_Locatext2, -32);
    lv_obj_set_align(ui_Locatext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locatext2, "Loca2");
    lv_obj_set_style_text_font(ui_Locatext2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Locatext3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locatext3, 65);
    lv_obj_set_height(ui_Locatext3, 18);
    lv_obj_set_x(ui_Locatext3, 53);
    lv_obj_set_y(ui_Locatext3, -9);
    lv_obj_set_align(ui_Locatext3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locatext3, "Loca3");
    lv_obj_set_style_text_font(ui_Locatext3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Locatext4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locatext4, 65);
    lv_obj_set_height(ui_Locatext4, 18);
    lv_obj_set_x(ui_Locatext4, 53);
    lv_obj_set_y(ui_Locatext4, 14);
    lv_obj_set_align(ui_Locatext4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locatext4, "Loca4");
    lv_obj_set_style_text_font(ui_Locatext4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Locatext5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locatext5, 65);
    lv_obj_set_height(ui_Locatext5, 18);
    lv_obj_set_x(ui_Locatext5, 53);
    lv_obj_set_y(ui_Locatext5, 37);
    lv_obj_set_align(ui_Locatext5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locatext5, "Loca5");
    lv_obj_set_style_text_font(ui_Locatext5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Locatext6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Locatext6, 65);
    lv_obj_set_height(ui_Locatext6, 18);
    lv_obj_set_x(ui_Locatext6, 53);
    lv_obj_set_y(ui_Locatext6, 60);
    lv_obj_set_align(ui_Locatext6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Locatext6, "Loca6\n");
    lv_obj_set_style_text_font(ui_Locatext6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi, -51);
    lv_obj_set_y(ui_Wifi, -97);
    lv_obj_set_align(ui_Wifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi, "Wifi");
    lv_obj_set_style_text_font(ui_Wifi, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Wifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi2, 28);
    lv_obj_set_y(ui_Wifi2, -80);
    lv_obj_set_align(ui_Wifi2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi2, "Disconnect");
    lv_obj_set_style_text_font(ui_Wifi2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Wifi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi3, 25);
    lv_obj_set_y(ui_Wifi3, -97);
    lv_obj_set_align(ui_Wifi3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi3, "TCP");
    lv_obj_set_style_text_font(ui_Wifi3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Wifi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi4, -53);
    lv_obj_set_y(ui_Wifi4, -80);
    lv_obj_set_align(ui_Wifi4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi4, "30 dBm");
    lv_obj_set_style_text_font(ui_Wifi4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blink1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Blink1, 235);
    lv_obj_set_height(ui_Blink1, 69);
    lv_obj_set_x(ui_Blink1, -13);
    lv_obj_set_y(ui_Blink1, 129);
    lv_obj_set_align(ui_Blink1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Blink1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blink1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blink1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Blink1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blink2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Blink2, 235);
    lv_obj_set_height(ui_Blink2, 69);
    lv_obj_set_x(ui_Blink2, -10);
    lv_obj_set_y(ui_Blink2, -103);
    lv_obj_set_align(ui_Blink2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Blink2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blink2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blink2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Blink2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlinkLoca = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BlinkLoca, 192);
    lv_obj_set_height(ui_BlinkLoca, 27);
    lv_obj_set_x(ui_BlinkLoca, -1);
    lv_obj_set_y(ui_BlinkLoca, 83);
    lv_obj_set_align(ui_BlinkLoca, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BlinkLoca, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BlinkLoca, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlinkLoca, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireCheckLoca = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireCheckLoca, 150);
    lv_obj_set_height(ui_WireCheckLoca, 21);
    lv_obj_set_x(ui_WireCheckLoca, 2);
    lv_obj_set_y(ui_WireCheckLoca, 85);
    lv_obj_set_align(ui_WireCheckLoca, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireCheckLoca, "         [OK]LA01");
    lv_obj_set_style_text_font(ui_WireCheckLoca, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
