// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#include "../ui.h"


// COMPONENT CodeA

lv_obj_t * ui_CodeA_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_CodeA;
    cui_CodeA = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_CodeA, 65);
    lv_obj_set_height(cui_CodeA, 19);
    lv_obj_set_x(cui_CodeA, -56);
    lv_obj_set_y(cui_CodeA, -57);
    lv_obj_set_align(cui_CodeA, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_CodeA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CODEA_NUM);
    children[UI_COMP_CODEA_CODEA] = cui_CodeA;
    lv_obj_add_event_cb(cui_CodeA, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_CodeA, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_CodeA_create_hook(cui_CodeA);
    return cui_CodeA;
}

