#COMPONENT_ADD_INCLUDEDIRS := .
#COMPONENT_SRCDIRS := .
#ifdef CONFIG_APP_WIFI_SHOW_DEMO_INTRO_TEXT
#CPPFLAGS += -D RMAKER_DEMO_PROJECT_NAME=\"$(PROJECT_NAME)\"
#endif
COMPONENT_SRCS := TCP_CLIENT_V4.c
COMPONENT_ADD_INCLUDEDIRS := .
