// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#ifndef _CODE_LOCATION_COLOR_UI_H
#define _CODE_LOCATION_COLOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../managed_components/lvgl__lvgl/lvgl.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "esp_err.h"
#include "esp_log.h"
#include "string.h"
#include "freertos/timers.h"
#include "lvgl.h"
// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "TCP_CLIENT_V4.h"
#define LV_COLOR_16_SWAP 0

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Color11;
extern lv_obj_t * ui_Color21;
extern lv_obj_t * ui_Color31;
extern lv_obj_t * ui_Color41;
extern lv_obj_t * ui_Color51;
extern lv_obj_t * ui_Color61;
extern lv_obj_t * ui_Color11g;
extern lv_obj_t * ui_Color21g;
extern lv_obj_t * ui_Color31g;
extern lv_obj_t * ui_Color41g;
extern lv_obj_t * ui_Color51g;
extern lv_obj_t * ui_Color61g;
extern lv_obj_t * ui_WireText1;
extern lv_obj_t * ui_WireText2;
extern lv_obj_t * ui_WireText3;
extern lv_obj_t * ui_WireText4;
extern lv_obj_t * ui_WireText5;
extern lv_obj_t * ui_WireText6;
extern lv_obj_t * ui_Locatext1;
extern lv_obj_t * ui_Locatext2;
extern lv_obj_t * ui_Locatext3;
extern lv_obj_t * ui_Locatext4;
extern lv_obj_t * ui_Locatext5;
extern lv_obj_t * ui_Locatext6;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_Wifi2;
extern lv_obj_t * ui_Wifi3;
extern lv_obj_t * ui_Wifi4;
extern lv_obj_t * ui_Blink1;
extern lv_obj_t * ui_Blink2;
extern lv_obj_t * ui_BlinkLoca;
extern lv_obj_t * ui_WireCheckLoca;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);
void lcd_reset_daydien_text(uint8_t index);
void lcd_set_daydien_text(wire_infor* DayDien, uint8_t index);
void lcd_set_wifi_rssi (int8_t rssi) ;
void lcd_set_socket_status(uint8_t status);
void setWireText (uint8_t wireIndex, char* value, uint16_t valueLength);
lv_color_t map_color(const char* colorCode);

void start_blink_effect(lv_obj_t *obj1, lv_obj_t *obj2);
void end_blink_effect(lv_obj_t *obj1, lv_obj_t *obj2);

void start_blink_effect_OK(void);
void end_blink_effect_OK(void);
void start_blink_effect_NG(void);
void end_blink_effect_NG(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
