// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#ifndef _CODE_LOCATION_COLOR_UI_H
#define _CODE_LOCATION_COLOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Color11;
extern lv_obj_t * ui_Color21;
extern lv_obj_t * ui_Color31;
extern lv_obj_t * ui_Color41;
extern lv_obj_t * ui_Color51;
extern lv_obj_t * ui_Color61;
extern lv_obj_t * ui_Color11g;
extern lv_obj_t * ui_Color21g;
extern lv_obj_t * ui_Color31g;
extern lv_obj_t * ui_Color41g;
extern lv_obj_t * ui_Color51g;
extern lv_obj_t * ui_Color61g;
extern lv_obj_t * ui_WireText1;
extern lv_obj_t * ui_WireText2;
extern lv_obj_t * ui_WireText3;
extern lv_obj_t * ui_WireText4;
extern lv_obj_t * ui_WireText5;
extern lv_obj_t * ui_WireText6;
extern lv_obj_t * ui_Locatext1;
extern lv_obj_t * ui_Locatext2;
extern lv_obj_t * ui_Locatext3;
extern lv_obj_t * ui_Locatext4;
extern lv_obj_t * ui_Locatext5;
extern lv_obj_t * ui_Locatext6;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_Wifi2;
extern lv_obj_t * ui_Wifi3;
extern lv_obj_t * ui_Wifi4;
extern lv_obj_t * ui_Blink1;
extern lv_obj_t * ui_Blink2;
extern lv_obj_t * ui_BlinkLoca;
extern lv_obj_t * ui_WireCheckLoca;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
