// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#include "../ui.h"

void ui_comp_CodeA_create_hook(lv_obj_t * comp)
{
}
