// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#ifndef _UI_COMP_CODEA_H
#define _UI_COMP_CODEA_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT CodeA
#define UI_COMP_CODEA_CODEA 0
#define _UI_COMP_CODEA_NUM 1
lv_obj_t * ui_CodeA_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
