// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Color11;
lv_obj_t * ui_Color21;
lv_obj_t * ui_Color31;
lv_obj_t * ui_Color41;
lv_obj_t * ui_Color51;
lv_obj_t * ui_Color61;
lv_obj_t * ui_Color11g;
lv_obj_t * ui_Color21g;
lv_obj_t * ui_Color31g;
lv_obj_t * ui_Color41g;
lv_obj_t * ui_Color51g;
lv_obj_t * ui_Color61g;
lv_obj_t * ui_WireText1;
lv_obj_t * ui_WireText2;
lv_obj_t * ui_WireText3;
lv_obj_t * ui_WireText4;
lv_obj_t * ui_WireText5;
lv_obj_t * ui_WireText6;
lv_obj_t * ui_Locatext1;
lv_obj_t * ui_Locatext2;
lv_obj_t * ui_Locatext3;
lv_obj_t * ui_Locatext4;
lv_obj_t * ui_Locatext5;
lv_obj_t * ui_Locatext6;
lv_obj_t * ui_Wifi;
lv_obj_t * ui_Wifi2;
lv_obj_t * ui_Wifi3;
lv_obj_t * ui_Wifi4;
lv_obj_t * ui_Blink1;
lv_obj_t * ui_Blink2;
lv_obj_t * ui_BlinkLoca;
lv_obj_t * ui_WireCheckLoca;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
