



// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Code_Location_Color

#include "../ui.h"
#include "TCP_CLIENT_V4.h"
#include "ESP32_Infor.h"



#if 1 //Giao dien FacB
void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xB7B6BA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color1, 228);
    lv_obj_set_height(ui_Color1, 38);
    lv_obj_set_x(ui_Color1, 0);
    lv_obj_set_y(ui_Color1, 15);
    lv_obj_set_align(ui_Color1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color1, lv_color_hex(0xEA451B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Color1, lv_color_hex(0x4C9F9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Color1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color1g = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Color1g, 228);
    lv_obj_set_height(ui_Color1g, 13);
    lv_obj_set_x(ui_Color1g, 0);
    lv_obj_set_y(ui_Color1g, 15);
    lv_obj_set_align(ui_Color1g, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Color1g, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color1g, lv_color_hex(0x0E33F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color1g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi, -51);
    lv_obj_set_y(ui_Wifi, -97);
    lv_obj_set_align(ui_Wifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi, "Wifi");
    lv_obj_set_style_text_font(ui_Wifi, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Wifi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi4, -43);
    lv_obj_set_y(ui_Wifi4, -77);
    lv_obj_set_align(ui_Wifi4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifi4, " ");
    lv_obj_set_style_text_font(ui_Wifi4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatus = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_WifiStatus, 19);
    lv_obj_set_height(ui_WifiStatus, 16);
    lv_obj_set_x(ui_WifiStatus, -70);
    lv_obj_set_y(ui_WifiStatus, -78);
    lv_obj_set_align(ui_WifiStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TCP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TCP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TCP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TCP, -7);
    lv_obj_set_y(ui_TCP, -97);
    lv_obj_set_align(ui_TCP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TCP, "TCP");
    lv_obj_set_style_text_font(ui_TCP, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TCPStatus = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TCPStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TCPStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TCPStatus, -6);
    lv_obj_set_y(ui_TCPStatus, -78);
    lv_obj_set_align(ui_TCPStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TCPStatus, "NG");
    lv_obj_set_style_text_color(ui_TCPStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TCPStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TCPStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bat = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Bat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bat, 37);
    lv_obj_set_y(ui_Bat, -97);
    lv_obj_set_align(ui_Bat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Bat, "Bat");
    lv_obj_set_style_text_font(ui_Bat, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PercentBat = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PercentBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PercentBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PercentBat, 41);
    lv_obj_set_y(ui_PercentBat, -78);
    lv_obj_set_align(ui_PercentBat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PercentBat, "100%");
    lv_obj_set_style_text_font(ui_PercentBat, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SAText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SAText, 124);
    lv_obj_set_height(ui_SAText, 46);
    lv_obj_set_x(ui_SAText, 23);
    lv_obj_set_y(ui_SAText, -35);
    lv_obj_set_align(ui_SAText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SAText, " ");
    lv_obj_set_style_text_color(ui_SAText, lv_color_hex(0xF10B38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SAText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SAText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroupText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_GroupText, 115);
    lv_obj_set_height(ui_GroupText, 46);
    lv_obj_set_x(ui_GroupText, 25);
    lv_obj_set_y(ui_GroupText, 57);
    lv_obj_set_align(ui_GroupText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GroupText, " ");
    lv_obj_set_style_text_color(ui_GroupText, lv_color_hex(0x150FF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GroupText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GroupText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blink1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Blink1, 235);
    lv_obj_set_height(ui_Blink1, 69);
    lv_obj_set_x(ui_Blink1, -1);
    lv_obj_set_y(ui_Blink1, 124);
    lv_obj_set_align(ui_Blink1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Blink1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blink1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blink1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Blink1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Blink2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Blink2, 235);
    lv_obj_set_height(ui_Blink2, 69);
    lv_obj_set_x(ui_Blink2, 5);
    lv_obj_set_y(ui_Blink2, -100);
    lv_obj_set_align(ui_Blink2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Blink2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Blink2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blink2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Blink2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeCL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ModeCL, 33);
    lv_obj_set_height(ui_ModeCL, 20);
    lv_obj_set_x(ui_ModeCL, 8);
    lv_obj_set_y(ui_ModeCL, 106);
    lv_obj_set_align(ui_ModeCL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeCL, " ");
    lv_obj_set_style_text_font(ui_ModeCL, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireCount = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_WireCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WireCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WireCount, 79);
    lv_obj_set_y(ui_WireCount, -76);
    lv_obj_set_align(ui_WireCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireCount, "0");
    lv_obj_set_style_text_font(ui_WireCount, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);


}

#endif




void setWireText (uint8_t wireIndex, char* value, uint16_t valueLength) {
    char WireTemp[50] = {0};
    if(valueLength > 50)  valueLength = 50;
    memcpy(WireTemp, value, valueLength);
    switch(wireIndex) {
        case 0:
            lv_label_set_text(ui_SAText, WireTemp);
        break;
        // case 1:
        //     lv_label_set_text(ui_WireText2, WireTemp);
        // break;
        // case 2:
        //     lv_label_set_text(ui_WireText3, WireTemp);
        // break;
        // case 3:
        //     lv_label_set_text(ui_WireText4, WireTemp);
        // break;
        // case 4:
        //     lv_label_set_text(ui_WireText5, WireTemp);
        // break;
        // case 5:
        //     lv_label_set_text(ui_WireText6, WireTemp);
        // break;
        default:
            
        break;
    }
}
void lcd_set_wifi_rssi (int8_t rssi) 
{
    char buffer[15] = {0};
    sprintf(buffer, "%3" PRIi8 " ", rssi);
    lv_label_set_text(ui_Wifi4, buffer);
}
void lcd_aliveWire (int8_t wireCount) 
{
    char buffer[15] = {0};
    sprintf(buffer, "%3" PRIi8 " ", wireCount);
    lv_label_set_text(ui_WireCount, buffer);
}
void lcd_set_wifi_color (uint8_t isConnectedWifi, int8_t rssi)
{
    if(isConnectedWifi == 0) {
        // Đen: Chưa kết nối
        lv_obj_set_style_bg_color(ui_WifiStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        return;
    }
    // Kiểm tra giá trị RSSI và đặt màu nền tương ứng
    if (rssi > -40 && rssi < 0 ) {
        // Xanh lá: Tín hiệu tốt
        lv_obj_set_style_bg_color(ui_WifiStatus, lv_color_hex(0x08A618), LV_PART_MAIN | LV_STATE_DEFAULT);  //0x044604
    } else if (rssi >= -60 && rssi < -40) {
        // Vàng: Tín hiệu trung bình
        lv_obj_set_style_bg_color(ui_WifiStatus, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        // Đỏ: Tín hiệu kém
        lv_obj_set_style_bg_color(ui_WifiStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

void lcd_set_bat_percent(int8_t bat) 
{
    if (bat < 0) bat = 0;      // Giới hạn giá trị nhỏ nhất
    if (bat > 100) bat = 100;  // Giới hạn giá trị lớn nhất
    
    char buffer[15] = {0};
    sprintf(buffer, "%3" PRIi8 "%%", bat);  // Thêm dấu % để hiển thị rõ ràng
    lv_label_set_text(ui_PercentBat, buffer);
}

 




void lcd_set_socket_status(uint8_t status)
{
    if(status == 0) {
    lv_label_set_text(ui_TCPStatus, "NG");
    lv_obj_set_style_text_color(ui_TCPStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TCPStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TCPStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    } 
    else if(status == 1) {
    lv_label_set_text(ui_TCPStatus, "OK");
    lv_obj_set_style_text_color(ui_TCPStatus, lv_color_hex(0x044604), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TCPStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TCPStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

void Check_ModeCL_Screen(Work_Mode status)
{
    if(status == SA_MODE) {
    lv_label_set_text(ui_ModeCL, "SA");
    } 
    else if(status == GROUP_MODE) {
    lv_label_set_text(ui_ModeCL, "GR");
    }
    else if(status == SA_GROUP_MODE) {
    lv_label_set_text(ui_ModeCL, "SG");
    }
}
// Hàm trim đơn giản: loại bỏ khoảng trắng đầu và cuối
void trim(char* str) {
    // Trim đầu
    char* start = str;
    while (isspace((unsigned char)*start)) start++;

    // Trim cuối
    char* end = start + strlen(start) - 1;
    while (end > start && isspace((unsigned char)*end)) end--;
    *(end + 1) = '\0';

    // Dịch chuỗi về đầu nếu cần
    if (start != str) {
        memmove(str, start, strlen(start) + 1);
    }
}

lv_color_t map_color(const char* colorCode) {
    trim(colorCode);
    if ((strcmp(colorCode, "B") == 0)||(strcmp(colorCode, "KH") == 0)) {
        return lv_color_hex(0x000000);  // TFT_BLACK
    } else if (strcmp(colorCode, "W") == 0) {
        return lv_color_hex(0xFFFFFF);  // 
    } else if (strcmp(colorCode, "KH") == 0) {
        return lv_color_hex(0x1F1F1F);  // 
    } else if (strcmp(colorCode, "R") == 0) {
        return lv_color_hex(0xFF0000);  // TFT_RED
    } else if (strcmp(colorCode, "G") == 0) {
        return lv_color_hex(0x008000);  // TFT_GREEN
    } else if (strcmp(colorCode, "L") == 0) {
        return lv_color_hex(0x0000FF);  // TFT_BLUE
    } else if (strcmp(colorCode, "C") == 0) {
        return lv_color_hex(0x00FFFF);  // TFT_CYAN
    } else if (strcmp(colorCode, "M") == 0) {
        return lv_color_hex(0xFF00FF);  // TFT_MAGENTA
    } else if (strcmp(colorCode, "Y") == 0) {
        return lv_color_hex(0xFFFF00);  // TFT_YELLOW
    } else if (strcmp(colorCode, "O") == 0) {
        return lv_color_hex(0xFF8040);  // TFT_ORANGEF96A06
    } else if (strcmp(colorCode, "P") == 0) {
        return lv_color_hex(0xF58BBD);  // TFT_PINK
    } else if (strcmp(colorCode, "V") == 0) {
        return lv_color_hex(0x800080);  // TFT_PURPLE
    } else if (strcmp(colorCode, "BR") == 0) {
        return lv_color_hex(0xB06868);  // TFT_BROWN
    } else if (strcmp(colorCode, "GR") == 0) {
        return lv_color_hex(0x808080);  // TFT_LIGHTGRAY
    } else if (strcmp(colorCode, "LG") == 0) {
        return lv_color_hex(0x00FF00);  // TFT_GREENYELLOW
    } else if (strcmp(colorCode, "LA") == 0) {
        return lv_color_hex(0xE2C6DD);  // TFT_LAVENDER (Cyan + Magenta)/2
    } else if (strcmp(colorCode, "BG") == 0) {
        return lv_color_hex(0xD7BD83);  // TFT_BEIGE (White + Brown)/2
    } else if (strcmp(colorCode, "SB") == 0) {
        return lv_color_hex(0x4DB8EC);  // TFT_SKYBLUE
    } else if (strcmp(colorCode, "DB") == 0) {
        return lv_color_hex(0x000080);  // TFT_DARKBLUE (Blue + Black)/2
    } else if (strcmp(colorCode, "DG") == 0) {
        return lv_color_hex(0x006400);  // TFT_DARKGREEN
    } else if (strcmp(colorCode, "N") == 0) {
        return lv_color_hex(0x800000);  // TFT_VERYLIGHTPINK (Pink + White)/2
    } else if (strcmp(colorCode, "None") == 0) {
        return lv_color_hex(0xFFFFFF);  // Default White
    } else if (strcmp(colorCode, "DR") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    } else if (strcmp(colorCode, "DRAIN") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    } else if (strcmp(colorCode, "SHLD") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    } else if (strcmp(colorCode, "DRAIN") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    } else if (strcmp(colorCode, "SH") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    } else if (strcmp(colorCode, "LD") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    } else if (strcmp(colorCode, "SI") == 0) {
        return lv_color_hex(0xEFEFEF);  // Default White
    }
     else {
        return lv_color_hex(0xFFFFFF);  // Default White
    }
}

//Mảng kiểm soát số lượng màu ứng với từng dây hiển thị trên màn hình. 0 - Không hiển thị || 1 - Dây có 1 màu || 2 - Dây có 2 màu
uint8_t wireColorCountArr[6] = {0};

void lcd_set_daydien_text(wire_infor* DayDien, uint8_t index, Work_Mode Mode) {
    if(index == 0) {      
                       
        lv_obj_set_style_bg_color(ui_Color1, map_color(DayDien->colors.color[0].main_color), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Color1g, map_color(DayDien->colors.color[0].sub_color), LV_PART_MAIN | LV_STATE_DEFAULT);
        
        if(Mode == SA_MODE)
        {
            lv_label_set_text(ui_SAText, DayDien->Sa);
        }
        else if(Mode == GROUP_MODE)
        {
            lv_label_set_text(ui_GroupText, DayDien->group);
        }

        else if(Mode == SA_GROUP_MODE)
        {
            lv_label_set_text(ui_SAText, DayDien->Sa);
            lv_label_set_text(ui_GroupText, DayDien->group);
        }
        //Gán giá trị số màu dây
        wireColorCountArr[0] = DayDien->colors.color_count;
    }
}

void lcd_reset_daydien_text(uint8_t index) {
    if(index == 0) {
        lv_label_set_text(ui_SAText,"");
        lv_label_set_text(ui_GroupText,"");
        lv_obj_set_style_bg_color(ui_Color1, map_color(ui_Color1), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(ui_Color1g, map_color(ui_Color1g), LV_PART_MAIN | LV_STATE_DEFAULT);

        //Gán giá trị số màu dây
        wireColorCountArr[index] = 0;
 
    }
   
}


// Hàm bắt đầu hiệu ứng nhấp nháy
void start_blink_effect(lv_obj_t *obj1, lv_obj_t *obj2) {
    lv_obj_t *objs[] = {obj1, obj2};  // Mảng chứa các đối tượng

    // Đặt độ trong suốt của các đối tượng lên 255 (hiển thị)
    lv_obj_set_style_bg_opa(objs[0], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(objs[1], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
}

// Hàm kết thúc hiệu ứng nhấp nháy
void end_blink_effect(lv_obj_t *obj1, lv_obj_t *obj2) {
    lv_obj_t *objs[] = {obj1, obj2};  // Mảng chứa các đối tượng

    // Đặt độ trong suốt của các đối tượng lên 255 (hiển thị)
    lv_obj_set_style_bg_opa(objs[0], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(objs[1], 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}





ScreenCL_Mode get_screen_mode(const char* code) {
    if (code == NULL || strlen(code) < 3) {
        return PN_Mode; // hoặc xử lý lỗi tùy ý
    }

    // Kiểm tra nếu toàn bộ chuỗi là "TRF4" hoặc "PCX"
    if (strcmp(code, "TAF4") == 0 || strcmp(code, "PCX") == 0) {
        return PN_Mode;
    }

    char third_char = code[2];

    // Kiểm tra ký tự thứ 3
    if (third_char == 'E' || third_char == 'O' || third_char == 'R') {
        return PN_Mode;
    }

    if (third_char == 'I' || third_char == 'M' || third_char == 'F' || third_char == '0' || third_char == '1' || third_char == '2'
    || third_char == '3' || third_char == '4' || third_char == '5' || third_char == '6' || third_char == '7' || third_char == '8' 
    || third_char == '9' || third_char == 'Z' || third_char == 'Y' || third_char == 'D' || third_char == 'B') {
        return Lot_Mode;
    }

    // Mặc định nếu không khớp gì
    return PN_Mode;
}


//Ẩn đối tượng
void set_HideObject(lv_obj_t * ui_Object) {


    lv_obj_add_flag(ui_Object, LV_OBJ_FLAG_HIDDEN);  // Ẩn Panel
    
}

//Hiển thị đối tượng
void set_ShowObject(lv_obj_t * ui_Object) {
    // lv_obj_set_style_bg_opa(ui_Object, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Object, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    // // // lv_obj_set_style_border_width(ui_Object, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // // // lv_obj_set_style_shadow_width(ui_Object, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // // // Làm chữ hiển thị (text opacity)
    // lv_obj_set_style_text_opa(ui_Object, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_clear_flag(ui_Object, LV_OBJ_FLAG_HIDDEN); // Hiển thị Panel
}




uint8_t old_numberCard = 6;
uint8_t old_wireColorCountArr[6] = {0};


void set_numberCardOnScreenCL(uint8_t numberCard) {
    //Giới hạn giá trị truyền vào
    if(numberCard > 6) numberCard = 6;

    uint8_t isNeedChangeScreen = 0; //Biến kiểm tra xem thông tin màn hình có thay đổi và cần load lại màn hình không
    //Kiểm tra xem tổng số thẻ có thay đổi không
    if(old_numberCard != numberCard) {
        old_numberCard = numberCard;
    }
    else {
        isNeedChangeScreen++;
    }
    //Kiểm tra xem thông tin dây trên màn hình có thay đổi không
    isNeedChangeScreen++;
    for(uint8_t i = 0; i < numberCard; i++) {
        if(old_wireColorCountArr[i] != wireColorCountArr[i]) {
            isNeedChangeScreen--;
            old_wireColorCountArr[i] = wireColorCountArr[i];
            break;
        }
    }
    //Nếu cờ isNeedChangeScreen bằng 2 chứng tỏ số numberCard không đổi và thông tin trên màn cũng không đổi
    if(isNeedChangeScreen == 2) {
        //Thoát khỏi hàm bởi màn hình đã được hiển thị đúng số lượng thẻ
        return;
    }
    printf("Thực hiện thay đỔI");
    // printf("Check color count arr: %d %d %d %d %d %d\n", wireColorCountArr[0], wireColorCountArr[1], wireColorCountArr[2], wireColorCountArr[3], wireColorCountArr[4], wireColorCountArr[5]);
    if(numberCard == 0) {

        set_HideObject(ui_Color1);
        set_HideObject(ui_Color1g);
        set_HideObject(ui_SAText);
        set_HideObject(ui_GroupText);

    }
    else if(numberCard == 1) {
    
        //Nếu thẻ chỉ có 1 màu
        if(wireColorCountArr[0] == 1) {

            lv_obj_set_width(ui_Color1, 228);
            lv_obj_set_height(ui_Color1, 38);
            lv_obj_set_x(ui_Color1, 0);
            lv_obj_set_y(ui_Color1, 15);
            //Hiển thị
            // lv_obj_set_style_bg_opa(ui_Color11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            set_ShowObject(ui_Color1);

            lv_obj_set_width(ui_Color1g, 228);
            lv_obj_set_height(ui_Color1g, 13);
            lv_obj_set_x(ui_Color1g, 0);
            lv_obj_set_y(ui_Color1g, 15);
            //Hiển thị
            // lv_obj_set_style_bg_opa(ui_Color11g, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            // lv_obj_set_style_bg_opa(ui_Color11g, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
            set_ShowObject(ui_Color1g);
        }


            lv_obj_set_width(ui_SAText, 124);
            lv_obj_set_height(ui_SAText, 46);
            lv_obj_set_x(ui_SAText, 23);
            lv_obj_set_y(ui_SAText, -35);
            lv_obj_set_style_text_font(ui_SAText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
            //Hiển thị
            // lv_obj_set_style_bg_opa(ui_WireText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            set_ShowObject(ui_SAText);

            lv_obj_set_width(ui_GroupText, 115);
            lv_obj_set_height(ui_GroupText, 46);
            lv_obj_set_x(ui_GroupText, 25);
            lv_obj_set_y(ui_GroupText, 57);
            lv_obj_set_style_text_font(ui_GroupText, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
            //Hiển thị
            // lv_obj_set_style_bg_opa(ui_Locatext1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            set_ShowObject(ui_GroupText);

    }

}






